# Training Hyperparameters
batch_size: 1
epochs: 1000
accum_iter: 1

# Optimizer Settings
lr: 1.0e-4
# lr: null  # Will be calculated based on blr
blr: 1.0e-4
min_lr: 1.0e-6
weight_decay: 0.05
# warmup_epochs: 40
warmup_epochs: 10
clip_grad: null
layer_decay: 0.75

# Model Architecture
model: "point_vec1024_dim1024_depth24"
# model: "point_vec512_dim512_depth24"
# model: "learnable_vec512_dim512_depth24"
# point_cloud_size: 8192
# point_cloud_size: 65536
point_cloud_size: 14147
# model: "custom_model"
# latent_vec: 1024 # Latent Vector 개수
# latent_dim: 1024 # Latent Vector 하나의 차원
# query_type: "point" # point, learnable
# model_depth: 24

# Dataset Settings
dataset_type: "ct_single" 
# data_path: "dummy_ct.nii.gz"
data_path: "/gpfs/accounts/jjparkcv_root/jjparkcv98/minsukc/LIDC/LIDC_NII_Data/LIDC_0000.nii.gz"
num_workers: 0 # Set to 0 for debugging/single file to avoid fork issues
pin_mem: true

# Distributed Training (Defaults for single GPU)
world_size: 1
dist_on_itp: false
dist_url: "env://"

# Output
output_dir: "./output/ct_overfit_experiment"
checkpoint_dir: "/gpfs/accounts/jjparkcv_root/jjparkcv98/minsukc/vecset/ct_overfit_experiment"
log_dir: "./output/ct_overfit_experiment"
seed: 42
resume: null
start_epoch: 0
eval: false
dist_eval: false
device: "cuda"
wandb: true